/**
 * Theme Generator
 *
 * Reads design tokens from src/lib/design-system/tokens.ts and writes
 * src/lib/design-system/generated-theme.css with :root, .dark, and scrollbar styles.
 *
 * Usage: npx tsx scripts/generate-theme.ts
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { tokens } from "../src/lib/design-system/tokens";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = resolve(__dirname, "../src/lib/design-system/generated-theme.css");

function camelToKebab(str: string): string {
  return str
    .replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`)
    .replace(/(\D)(\d)/g, "$1-$2");
}

const SCROLLBAR_KEYS = ["scrollbarTrack", "scrollbarThumb", "scrollbarThumbHover"] as const;

function buildVarBlock(colors: Record<string, string>, indent: string): string {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(colors)) {
    if ((SCROLLBAR_KEYS as readonly string[]).includes(key)) continue;
    lines.push(`${indent}--${camelToKebab(key)}: ${value};`);
  }
  return lines.join("\n");
}

function buildScrollbar(colors: Record<string, string>, selector: string): string {
  const track = colors.scrollbarTrack;
  const thumb = colors.scrollbarThumb;
  const thumbHover = colors.scrollbarThumbHover;
  const prefix = selector ? `${selector} ` : "";
  return [
    `${prefix}::-webkit-scrollbar-track { background: ${track}; }`,
    `${prefix}::-webkit-scrollbar-thumb { background: ${thumb}; border-radius: 3px; }`,
    `${prefix}::-webkit-scrollbar-thumb:hover { background: ${thumbHover}; }`,
  ].join("\n");
}

const css = `/* Auto-generated by scripts/generate-theme.ts — do not edit manually */
/* Run: npm run generate:theme */

:root {
  --radius: ${tokens.radius};
${buildVarBlock(tokens.colors.light, "  ")}
}

.dark {
${buildVarBlock(tokens.colors.dark, "  ")}
}

::-webkit-scrollbar { width: 6px; }
${buildScrollbar(tokens.colors.light, "")}

${buildScrollbar(tokens.colors.dark, ".dark")}
`;

const lightKeys = Object.keys(tokens.colors.light).sort();
const darkKeys = Object.keys(tokens.colors.dark).sort();
const missingInDark = lightKeys.filter((k) => !darkKeys.includes(k));
const missingInLight = darkKeys.filter((k) => !lightKeys.includes(k));

if (missingInDark.length || missingInLight.length) {
  console.error("✗ Token key mismatch between light and dark modes:");
  if (missingInDark.length) {
    console.error(`  Missing in dark: ${missingInDark.join(", ")}`);
  }
  if (missingInLight.length) {
    console.error(`  Missing in light: ${missingInLight.join(", ")}`);
  }
  process.exit(1);
}

writeFileSync(OUTPUT, css, "utf-8");
console.log(`✓ Generated ${OUTPUT}`);
